### PR TITLE
Sync remaining labels via `github-label-sync`

### PR DESCRIPTION
**Pull request by ybiquitous**
We need to sync the remaining labels below:
- "status: agreed but held"
- "type: security"

E.g.

```sh-session
$ npx github-label-sync "stylelint/stylelint" --dry-run
...
 > Added: the "syntax: css-in-js" label in the repo is not expected. It will be deleted.
 > Added: the "syntax: html" label in the repo is not expected. It will be deleted.
 > Added: the "syntax: less" label in the repo is not expected. It will be deleted.
 > Added: the "syntax: markdown" label in the repo is not expected. It will be deleted.
 > Added: the "syntax: postcss" label in the repo is not expected. It will be deleted.
 > Added: the "syntax: sass" label in the repo is not expected. It will be deleted.
 > Added: the "syntax: scss" label in the repo is not expected. It will be deleted.
 > Added: the "type: new autofix" label in the repo is not expected. It will be deleted.
 > Added: the "type: new option" label in the repo is not expected. It will be deleted.
 > Added: the "type: new rule" label in the repo is not expected. It will be deleted.
...

$ npx github-label-sync "stylelint/create-stylelint" --dry-run
...
 > Missing: the "status: agreed but held" label is missing from the repo. It will be created.
 > Missing: the "type: security" label is missing from the repo. It will be created.
...
```

> Which issue, if any, is this issue related to?

Follow-up to #31

> Is there anything in the PR that needs further explanation?

We must to sync labels in the following labels via:

```shell
# Check
npx github-label-sync "${repo}" --allow-added-labels --dry-run

# Run
npx github-label-sync "${repo}" --allow-added-labels
```

Target repos:

- [ ] [stylelint/changelog-to-github-release-action](https://github.com/stylelint/changelog-to-github-release-action)
- [ ] [stylelint/create-stylelint](https://github.com/stylelint/create-stylelint)
- [ ] [stylelint/eslint-config-stylelint](https://github.com/stylelint/eslint-config-stylelint)
- [ ] [stylelint/jest-preset-stylelint](https://github.com/stylelint/jest-preset-stylelint)
- [ ] [stylelint/npm-package-json-lint-config](https://github.com/stylelint/npm-package-json-lint-config)
- [ ] [stylelint/prettier-config](https://github.com/stylelint/prettier-config)
- [ ] [stylelint/remark-preset](https://github.com/stylelint/remark-preset)
- [x] ~~[stylelint/stylelint](https://github.com/stylelint/stylelint)~~
- [ ] [stylelint/stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended)
- [ ] [stylelint/stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard)
- [ ] [stylelint/stylelint-demo](https://github.com/stylelint/stylelint-demo)
- [ ] [stylelint/stylelint-test-rule-node](https://github.com/stylelint/stylelint-test-rule-node)
- [ ] [stylelint/stylelint.io](https://github.com/stylelint/stylelint.io)

### CODE REVIEW

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you!

> [stylelint/stylelint](https://github.com/stylelint/stylelint)

I assume we won't run for this repo because it'll delete the custom labels we need for this repo like `syntax: *` and `type: new rule`?

**Comment by ybiquitous** [comment]
> I assume we won't run for this repo because it'll delete the custom labels we need for this repo like `syntax: *` and `type: new rule`?

Right, we don't need this operation for `stylelint/stylelint`. I've excluded the repo. 👍🏼

**Comment by ybiquitous** [comment]
I'm going to update the labels now.

**Comment by ybiquitous** [comment]
All done!

**Pull request merged**
